<?php
/**
 * Created by PhpStorm.
 * User: flyingfox
 * Date: 2020/1/6
 * Time: 18:27
 */

namespace app\modules\models;

use yii\base\Model;
use yii\data\ActiveDataProvider;
use app\modules\models\ShopAdmin;

class AdminSearch extends ShopAdmin
{
    public function rules(){
        return [
            ['adminid','integer'],
            [['adminuser','adminpass','adminemail','logintime','loginip','createtime','rememberMe','repeatpass'],'safe'],
        ];
    }

    public function scenarios()
    {
        return Model::scenarios(); // TODO: Change the autogenerated stub
    }

    public function search($params){
        $query = ShopAdmin::find();

        $dataProvider = new ActiveDataProvider([
            'query' => $query,
            'pagination' => [
                'pageSize' => 1,
            ],
        ]);

        $this->load($params);

        if(!$this->validate()){
            return $dataProvider;
        }

        $query->andFilterWhere([
            'adminid' => $this->adminid
        ]);

        $query->andFilterWhere(['like','adminuser',$this->adminuser])
            ->andFilterWhere(['like','adminpass',$this->adminpass]);

        return $dataProvider;

    }
}